CREATE EXTENSION IF NOT EXISTS pgcrypto;

DROP TABLE IF EXISTS p_characters;

START TRANSACTION;

CREATE TABLE p_characters (
  character_id INTEGER GENERATED BY DEFAULT AS IDENTITY (
    START
    WITH
      1000
  ) PRIMARY KEY,
  public_id UUID NOT NULL UNIQUE DEFAULT GEN_RANDOM_UUID(),
  name VARCHAR(16) NOT NULL UNIQUE CHECK (name ~ '^[A-Za-z]{3,}$'),
  hair_color CHAR(7) NOT NULL CHECK (hair_color ~ '^#[0-9A-Fa-f]{6}$'),
  hp_max INTEGER NOT NULL CHECK (hp_max >= 0),
  hp INTEGER NOT NULL CHECK (hp >= 0) CHECK (hp_max >= hp),
  blood_type VARCHAR(5) CHECK (blood_type IN ('A', 'B', 'O', 'AB')),
  height_cm DECIMAL(4, 1) NOT NULL CHECK (height_cm BETWEEN 50 AND 250),
  created_on DATE NOT NULL CHECK (created_on >= '2025-12-01') CHECK (created_on <= CURRENT_DATE),
  deleted_on DATE CHECK (deleted_on >= created_on)
);

-- 正常に挿入可能
INSERT INTO
  p_characters (character_id, name, hair_color, hp_max, hp, height_cm, created_on)
VALUES
  (1, 'TEST', '#000000', 512, 256, 200, '2025-12-01');

INSERT INTO
  p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
VALUES
  ('Alice', '#A1B2C3', 120, 100, 'A', 162.5, '2025-12-05'),
  ('Bob', '#3344FF', 150, 149, 'O', 175.0, '2025-12-07');

-- 制約違反で挿入失敗 (コメントを解除して検証してください)
--
-- 1. name の一意制約違反（すでに 'Alice' が存在すると仮定）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Alice', '#112233', 100, 80, 'A', 160.0, '2025-12-02');
--
-- 2. name が短すぎる（3文字未満で CHECK (name ~ '^[A-Za-z]{3,}$') に違反）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Al', '#112233', 100, 80, 'A', 160.0, '2025-12-02');
--
-- 3. hair_color が「#」なしで正規表現に違反
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Charlie', '112233', 100, 80, 'B', 170.0, '2025-12-02');
--
-- 4. hp_max が負の値（CHECK (hp_max >= 0) に違反）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('David', '#445566', -10, 0, 'O', 165.0, '2025-12-02');
--
-- 5. hp が負の値（CHECK (hp >= 0) に違反）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Eve', '#778899', 100, -5, 'AB', 155.0, '2025-12-02');
--
-- 6. hp が hp_max を超えている（CHECK (hp_max >= hp) に違反）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Frank', '#ABCDEF', 50, 60, 'A', 180.0, '2025-12-02');
--
-- 7. blood_type が候補外（IN ('A','B','O','AB') に違反）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Grace', '#123456', 100, 50, 'C', 160.0, '2025-12-02');
--
-- 8. height_cm が範囲外（50〜250 から外れている）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Heidi', '#654321', 100, 80, 'B', 49.9, '2025-12-02');
--
-- 9. created_on が 2025-12-01 より前（CHECK (created_on >= '2025-12-01') に違反）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
-- VALUES
--   ('Ivan', '#00FF00', 100, 80, 'O', 170.0, '2025-11-30');
--
-- 10. deleted_on が created_on より前（CHECK (deleted_on >= created_on) に違反）
-- INSERT INTO
--   p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on, deleted_on)
-- VALUES
--   ('Judy', '#FF00FF', 100, 80, 'AB', 165.0, '2025-12-02', '2025-12-01');

-- 確認
SELECT * FROM p_characters;

ROLLBACK;