CREATE EXTENSION IF NOT EXISTS pgcrypto;

START TRANSACTION;

DROP TABLE IF EXISTS x_gold_transfers;

DROP TABLE IF EXISTS x_character_items;

DROP TABLE IF EXISTS x_guild_characters;

DROP TABLE IF EXISTS x_guilds;

DROP TABLE IF EXISTS x_characters;

DROP TABLE IF EXISTS x_jobs;

DROP TABLE IF EXISTS x_items;

-- アイテムのマスタテーブル
CREATE TABLE x_items (
  item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(32) NOT NULL UNIQUE,
  price INTEGER NOT NULL CHECK (price >= 0),
  weight_kg DECIMAL(4, 1) NOT NULL,
  description TEXT
);

-- ジョブ（職業）のマスタテーブル
CREATE TABLE x_jobs (
  job_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(16) NOT NULL UNIQUE,
  attack_gain INTEGER NOT NULL,
  defense_gain INTEGER NOT NULL,
  magic_gain INTEGER NOT NULL
);

-- キャラクタのマスタテーブル
CREATE TABLE x_characters (
  character_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(16) NOT NULL,
  level INTEGER NOT NULL CHECK (level BETWEEN 1 AND 255),
  job_id INTEGER NOT NULL REFERENCES x_jobs (job_id),
  created_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP(0),
  deleted_at TIMESTAMP,
  CHECK (
    deleted_at IS NULL OR
    deleted_at >= created_at
  )
);

-- ギルドのマスタテーブル
CREATE TABLE x_guilds (
  guild_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(16) NOT NULL UNIQUE,
  owner_id INTEGER NOT NULL REFERENCES x_characters (character_id) ON DELETE CASCADE
);

-- ギルドとキャラクタの所属関係を表す中間テーブル
-- (キャラクタは複数のギルドに所属することができるようになっています)
CREATE TABLE x_guild_characters (
  guild_id INTEGER REFERENCES x_guilds (guild_id) ON DELETE CASCADE,
  character_id INTEGER REFERENCES x_characters (character_id) ON DELETE CASCADE,
  PRIMARY KEY (character_id, guild_id)
);

-- キャラクタが所持するアイテムと数量を管理する中間テーブル
CREATE TABLE x_character_items (
  character_id INTEGER REFERENCES x_characters (character_id) ON DELETE CASCADE,
  item_id INTEGER REFERENCES x_items (item_id),
  qty INTEGER NOT NULL CHECK (qty >= 0),
  PRIMARY KEY (character_id, item_id)
);

-- キャラクタ同士、またはシステムとのゴールド送受信履歴を記録するトランザクションテーブル
--   from_character_id または to_character_id が NULL の場合、
--   その送受信相手は「システム」であることを表す。
CREATE TABLE x_gold_transfers (
  transfer_id UUID DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
  from_character_id INTEGER REFERENCES x_characters (character_id),
  to_character_id INTEGER REFERENCES x_characters (character_id),
  amount INTEGER NOT NULL CHECK (amount > 0),
  transferred_at TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP(0),
  CHECK (
    from_character_id IS NOT NULL OR
    to_character_id IS NOT NULL
  ),
  CHECK (
    from_character_id IS NULL OR
    to_character_id IS NULL OR
    from_character_id <> to_character_id
  )
);

COMMIT;