DROP TABLE IF EXISTS p_characters;

START TRANSACTION;

CREATE TABLE p_characters (
    character_id INTEGER GENERATED BY DEFAULT AS IDENTITY (
        START
        WITH
            1000
    ) PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE DEFAULT GEN_RANDOM_UUID(),
    name VARCHAR(16) NOT NULL UNIQUE CHECK (name ~ '^[A-Za-z]{3,}$'),
    hair_color CHAR(7) NOT NULL CHECK (hair_color ~ '^#[0-9A-Fa-f]{6}$'),
    hp_max INTEGER NOT NULL CHECK (hp_max >= 0),
    hp INTEGER NOT NULL CHECK (hp >= 0) CHECK (hp_max >= hp),
    blood_type VARCHAR(2) CHECK (blood_type IN ('A', 'B', 'O', 'AB')),
    height_cm DECIMAL(4, 1) NOT NULL CHECK (height_cm BETWEEN 50 AND 250),
    created_on DATE NOT NULL CHECK (created_on >= '2025-12-01') CHECK (created_on <= CURRENT_DATE),
    deleted_on DATE CHECK (deleted_on >= created_on)
);

INSERT INTO
    p_characters (character_id, name, hair_color, hp_max, hp, height_cm, created_on)
VALUES
    (1, 'TEST', '#000000', 512, 256, 200, '2025-12-01');

INSERT INTO
    p_characters (name, hair_color, hp_max, hp, blood_type, height_cm, created_on)
VALUES
    ('Alice', '#A1B2C3', 120, 100, 'A', 162.5, '2025-12-05'),
    ('Bob', '#3344FF', 150, 149, 'O', 175.0, '2025-12-07');

ROLLBACK;