-- 既に同名のテーブルがあれば削除する
DROP TABLE IF EXISTS s_characters;

-- キャラクタ情報を保持するテーブルを作成する
CREATE TABLE s_characters (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(16) NOT NULL,
  job VARCHAR(16) NOT NULL,
  level INTEGER NOT NULL,
  buff DECIMAL(3, 2) NOT NULL,
  guild VARCHAR(32),
  last_login_at TIMESTAMP,
  created_on DATE NOT NULL,
  CHECK (level BETWEEN 1 AND 99)
);

-- テーブルにレコードを挿入する
INSERT INTO
  s_characters (name, job, level, buff, guild, created_on, last_login_at)
VALUES
  ('Marvin', 'Priest', 35, -0.15, 'Yamato', '2020-09-23', '2025-07-24 13:31:00'),
  ('Zach', 'Ninja', 62, 0.1, 'D.D.D', '2020-10-25', '2025-07-30 18:33:00'),
  ('Charlie', 'Wizard', 57, 0.0, NULL, '2020-12-05', '2025-07-29 20:37:00'),
  ('Tom', 'Fighter', 1, 0.0, NULL, '2020-12-05', NULL),
  ('Ivan', 'Monk', 39, -0.07, NULL, '2021-02-15', '2025-07-18 19:29:00'),
  ('Alice', 'Priest', 42, 0.0, 'Yamato', '2021-06-14', '2025-09-18 14:22:00'),
  ('Trudy', 'Fighter', 48, 0.0, 'Yamato', '2021-11-28', '2025-09-29 12:37:00'),
  ('Bob', 'Monk', 33, 0.05, 'hameln', '2022-03-22', '2025-08-03 09:11:00'),
  ('Walter', 'Samurai', 73, 0.0, NULL, '2022-04-06', '2025-09-14 22:10:00'),
  ('Oscar', 'Fighter', 44, 0.05, 'hameln', '2022-11-10', '2025-09-10 21:00:00'),
  ('Ellen', 'Wizard', 51, 0.1, 'D.D.D', '2022-08-30', '2025-09-25 23:55:00'),
  ('Dave', 'Samurai', 68, 0.0, 'Yamato', '2023-01-19', '2025-08-15 16:08:00'),
  ('Mallet', 'Wizard', 64, 0.1, 'D.D.D', '2023-02-02', '2025-08-27 18:50:00'),
  ('Eve', 'Ninja', 46, 0.1, 'D.D.D', '2023-09-07', '2025-10-07 10:17:00'),
  ('Trent', 'Priest', 50, 0.0, 'Yamato', '2023-10-04', '2025-10-11 17:20:00'),
  ('Steve', 'Samurai', 70, 0.05, 'hameln', '2024-01-27', '2025-10-06 09:14:00'),
  ('Wendy', 'Fighter', 56, 0.1, 'D.D.D', '2024-03-18', '2025-08-08 10:56:00'),
  ('Carol', 'Priest', 28, -0.2, NULL, '2024-05-11', '2025-10-03 11:42:00'),
  ('Jack', 'Wizard', 61, 0.05, 'hameln', '2024-07-12', '2025-09-02 15:43:00');
