--
-- PostgreSQL database dump
--

\restrict 34XxVdFXqv9OqToBbahybrKJJNcPayARtPIZFouOgWEOdkCCTzKLM85KJY1WrSR

-- Dumped from database version 17.6 (Debian 17.6-2.pgdg13+1)
-- Dumped by pg_dump version 17.6 (Debian 17.6-2.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: 
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: n_character_items; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.n_character_items (
    character_id integer NOT NULL,
    item_id integer NOT NULL,
    qty integer NOT NULL,
    CONSTRAINT n_character_items_qty_check CHECK ((qty >= 0))
);


ALTER TABLE public.n_character_items OWNER TO student;

--
-- Name: n_characters; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.n_characters (
    character_id integer NOT NULL,
    name character varying(16) NOT NULL,
    job_id integer
);


ALTER TABLE public.n_characters OWNER TO student;

--
-- Name: n_items; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.n_items (
    item_id integer NOT NULL,
    name character varying(32) NOT NULL
);


ALTER TABLE public.n_items OWNER TO student;

--
-- Name: n_jobs; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.n_jobs (
    job_id integer NOT NULL,
    name character varying(16) NOT NULL
);


ALTER TABLE public.n_jobs OWNER TO student;

--
-- Name: p_characters; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.p_characters (
    character_id integer NOT NULL,
    name character varying(16) NOT NULL,
    level integer NOT NULL,
    job_id integer,
    user_id integer
);


ALTER TABLE public.p_characters OWNER TO student;

--
-- Name: p_characters_character_id_seq; Type: SEQUENCE; Schema: public; Owner: student
--

ALTER TABLE public.p_characters ALTER COLUMN character_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.p_characters_character_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: p_jobs; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.p_jobs (
    job_id integer NOT NULL,
    name character varying(16) NOT NULL,
    attack_gain integer NOT NULL,
    defense_gain integer NOT NULL,
    magic_gain integer NOT NULL
);


ALTER TABLE public.p_jobs OWNER TO student;

--
-- Name: p_users; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.p_users (
    user_id integer NOT NULL,
    name character varying(16) NOT NULL,
    email character varying(32) NOT NULL
);


ALTER TABLE public.p_users OWNER TO student;

--
-- Name: s_characters; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.s_characters (
    id integer NOT NULL,
    name character varying(16) NOT NULL,
    job character varying(16) NOT NULL,
    level integer NOT NULL,
    buff numeric(3,2) NOT NULL,
    guild character varying(32),
    last_login_at timestamp without time zone,
    created_on date NOT NULL,
    CONSTRAINT s_characters_level_check CHECK (((level >= 1) AND (level <= 99)))
);


ALTER TABLE public.s_characters OWNER TO student;

--
-- Name: s_characters_id_seq; Type: SEQUENCE; Schema: public; Owner: student
--

ALTER TABLE public.s_characters ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.s_characters_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: s_users; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.s_users (
    id integer NOT NULL,
    name text NOT NULL,
    age integer
);


ALTER TABLE public.s_users OWNER TO student;

--
-- Name: x_character_items; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.x_character_items (
    character_id integer NOT NULL,
    item_id integer NOT NULL,
    qty integer NOT NULL,
    CONSTRAINT x_character_items_qty_check CHECK ((qty >= 0))
);


ALTER TABLE public.x_character_items OWNER TO student;

--
-- Name: x_characters; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.x_characters (
    character_id integer NOT NULL,
    name character varying(16) NOT NULL,
    level integer NOT NULL,
    job_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT LOCALTIMESTAMP(0) NOT NULL,
    deleted_at timestamp without time zone,
    CONSTRAINT x_characters_check CHECK (((deleted_at IS NULL) OR (deleted_at >= created_at))),
    CONSTRAINT x_characters_level_check CHECK (((level >= 1) AND (level <= 255)))
);


ALTER TABLE public.x_characters OWNER TO student;

--
-- Name: x_characters_character_id_seq; Type: SEQUENCE; Schema: public; Owner: student
--

ALTER TABLE public.x_characters ALTER COLUMN character_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.x_characters_character_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: x_gold_transfers; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.x_gold_transfers (
    transfer_id uuid DEFAULT gen_random_uuid() NOT NULL,
    from_character_id integer,
    to_character_id integer,
    amount integer NOT NULL,
    transferred_at timestamp without time zone DEFAULT LOCALTIMESTAMP(0) NOT NULL,
    CONSTRAINT x_gold_transfers_amount_check CHECK ((amount > 0)),
    CONSTRAINT x_gold_transfers_check CHECK (((from_character_id IS NOT NULL) OR (to_character_id IS NOT NULL))),
    CONSTRAINT x_gold_transfers_check1 CHECK (((from_character_id IS NULL) OR (to_character_id IS NULL) OR (from_character_id <> to_character_id)))
);


ALTER TABLE public.x_gold_transfers OWNER TO student;

--
-- Name: x_guild_characters; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.x_guild_characters (
    guild_id integer NOT NULL,
    character_id integer NOT NULL
);


ALTER TABLE public.x_guild_characters OWNER TO student;

--
-- Name: x_guilds; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.x_guilds (
    guild_id integer NOT NULL,
    name character varying(16) NOT NULL,
    owner_id integer NOT NULL
);


ALTER TABLE public.x_guilds OWNER TO student;

--
-- Name: x_guilds_guild_id_seq; Type: SEQUENCE; Schema: public; Owner: student
--

ALTER TABLE public.x_guilds ALTER COLUMN guild_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.x_guilds_guild_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: x_items; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.x_items (
    item_id integer NOT NULL,
    name character varying(32) NOT NULL,
    price integer NOT NULL,
    weight_kg numeric(4,1) NOT NULL,
    description text,
    CONSTRAINT x_items_price_check CHECK ((price >= 0))
);


ALTER TABLE public.x_items OWNER TO student;

--
-- Name: x_items_item_id_seq; Type: SEQUENCE; Schema: public; Owner: student
--

ALTER TABLE public.x_items ALTER COLUMN item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.x_items_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: x_jobs; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.x_jobs (
    job_id integer NOT NULL,
    name character varying(16) NOT NULL,
    attack_gain integer NOT NULL,
    defense_gain integer NOT NULL,
    magic_gain integer NOT NULL
);


ALTER TABLE public.x_jobs OWNER TO student;

--
-- Name: x_jobs_job_id_seq; Type: SEQUENCE; Schema: public; Owner: student
--

ALTER TABLE public.x_jobs ALTER COLUMN job_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.x_jobs_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: y_character_items; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.y_character_items (
    character_id integer NOT NULL,
    item_id integer NOT NULL,
    qty integer NOT NULL,
    CONSTRAINT y_character_items_qty_check CHECK ((qty >= 0))
);


ALTER TABLE public.y_character_items OWNER TO student;

--
-- Name: y_characters; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.y_characters (
    character_id integer NOT NULL,
    name character varying(16) NOT NULL,
    job_id integer NOT NULL,
    deleted_at timestamp without time zone
);


ALTER TABLE public.y_characters OWNER TO student;

--
-- Name: y_items; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.y_items (
    item_id integer NOT NULL,
    name character varying(32) NOT NULL
);


ALTER TABLE public.y_items OWNER TO student;

--
-- Name: y_jobs; Type: TABLE; Schema: public; Owner: student
--

CREATE TABLE public.y_jobs (
    job_id integer NOT NULL,
    name character varying(16) NOT NULL
);


ALTER TABLE public.y_jobs OWNER TO student;

--
-- Name: y_jobs_job_id_seq; Type: SEQUENCE; Schema: public; Owner: student
--

ALTER TABLE public.y_jobs ALTER COLUMN job_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.y_jobs_job_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: n_character_items n_character_items_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_character_items
    ADD CONSTRAINT n_character_items_pkey PRIMARY KEY (character_id, item_id);


--
-- Name: n_characters n_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_characters
    ADD CONSTRAINT n_characters_pkey PRIMARY KEY (character_id);


--
-- Name: n_items n_items_name_key; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_items
    ADD CONSTRAINT n_items_name_key UNIQUE (name);


--
-- Name: n_items n_items_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_items
    ADD CONSTRAINT n_items_pkey PRIMARY KEY (item_id);


--
-- Name: n_jobs n_jobs_name_key; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_jobs
    ADD CONSTRAINT n_jobs_name_key UNIQUE (name);


--
-- Name: n_jobs n_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_jobs
    ADD CONSTRAINT n_jobs_pkey PRIMARY KEY (job_id);


--
-- Name: p_characters p_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.p_characters
    ADD CONSTRAINT p_characters_pkey PRIMARY KEY (character_id);


--
-- Name: p_jobs p_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.p_jobs
    ADD CONSTRAINT p_jobs_pkey PRIMARY KEY (job_id);


--
-- Name: p_users p_users_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.p_users
    ADD CONSTRAINT p_users_pkey PRIMARY KEY (user_id);


--
-- Name: s_characters s_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.s_characters
    ADD CONSTRAINT s_characters_pkey PRIMARY KEY (id);


--
-- Name: s_users s_users_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.s_users
    ADD CONSTRAINT s_users_pkey PRIMARY KEY (id);


--
-- Name: x_character_items x_character_items_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_character_items
    ADD CONSTRAINT x_character_items_pkey PRIMARY KEY (character_id, item_id);


--
-- Name: x_characters x_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_characters
    ADD CONSTRAINT x_characters_pkey PRIMARY KEY (character_id);


--
-- Name: x_gold_transfers x_gold_transfers_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_gold_transfers
    ADD CONSTRAINT x_gold_transfers_pkey PRIMARY KEY (transfer_id);


--
-- Name: x_guild_characters x_guild_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_guild_characters
    ADD CONSTRAINT x_guild_characters_pkey PRIMARY KEY (character_id, guild_id);


--
-- Name: x_guilds x_guilds_name_key; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_guilds
    ADD CONSTRAINT x_guilds_name_key UNIQUE (name);


--
-- Name: x_guilds x_guilds_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_guilds
    ADD CONSTRAINT x_guilds_pkey PRIMARY KEY (guild_id);


--
-- Name: x_items x_items_name_key; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_items
    ADD CONSTRAINT x_items_name_key UNIQUE (name);


--
-- Name: x_items x_items_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_items
    ADD CONSTRAINT x_items_pkey PRIMARY KEY (item_id);


--
-- Name: x_jobs x_jobs_name_key; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_jobs
    ADD CONSTRAINT x_jobs_name_key UNIQUE (name);


--
-- Name: x_jobs x_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_jobs
    ADD CONSTRAINT x_jobs_pkey PRIMARY KEY (job_id);


--
-- Name: y_character_items y_character_items_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_character_items
    ADD CONSTRAINT y_character_items_pkey PRIMARY KEY (character_id, item_id);


--
-- Name: y_characters y_characters_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_characters
    ADD CONSTRAINT y_characters_pkey PRIMARY KEY (character_id);


--
-- Name: y_items y_items_name_key; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_items
    ADD CONSTRAINT y_items_name_key UNIQUE (name);


--
-- Name: y_items y_items_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_items
    ADD CONSTRAINT y_items_pkey PRIMARY KEY (item_id);


--
-- Name: y_jobs y_jobs_name_key; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_jobs
    ADD CONSTRAINT y_jobs_name_key UNIQUE (name);


--
-- Name: y_jobs y_jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_jobs
    ADD CONSTRAINT y_jobs_pkey PRIMARY KEY (job_id);


--
-- Name: n_character_items n_character_items_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_character_items
    ADD CONSTRAINT n_character_items_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.n_characters(character_id) ON DELETE CASCADE;


--
-- Name: n_character_items n_character_items_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_character_items
    ADD CONSTRAINT n_character_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.n_items(item_id);


--
-- Name: n_characters n_characters_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.n_characters
    ADD CONSTRAINT n_characters_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.n_jobs(job_id) ON DELETE SET NULL;


--
-- Name: p_characters p_characters_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.p_characters
    ADD CONSTRAINT p_characters_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.p_jobs(job_id) ON DELETE SET NULL;


--
-- Name: p_characters p_characters_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.p_characters
    ADD CONSTRAINT p_characters_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.p_users(user_id) ON DELETE SET NULL;


--
-- Name: x_character_items x_character_items_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_character_items
    ADD CONSTRAINT x_character_items_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.x_characters(character_id) ON DELETE CASCADE;


--
-- Name: x_character_items x_character_items_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_character_items
    ADD CONSTRAINT x_character_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.x_items(item_id);


--
-- Name: x_characters x_characters_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_characters
    ADD CONSTRAINT x_characters_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.x_jobs(job_id);


--
-- Name: x_gold_transfers x_gold_transfers_from_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_gold_transfers
    ADD CONSTRAINT x_gold_transfers_from_character_id_fkey FOREIGN KEY (from_character_id) REFERENCES public.x_characters(character_id);


--
-- Name: x_gold_transfers x_gold_transfers_to_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_gold_transfers
    ADD CONSTRAINT x_gold_transfers_to_character_id_fkey FOREIGN KEY (to_character_id) REFERENCES public.x_characters(character_id);


--
-- Name: x_guild_characters x_guild_characters_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_guild_characters
    ADD CONSTRAINT x_guild_characters_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.x_characters(character_id) ON DELETE CASCADE;


--
-- Name: x_guild_characters x_guild_characters_guild_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_guild_characters
    ADD CONSTRAINT x_guild_characters_guild_id_fkey FOREIGN KEY (guild_id) REFERENCES public.x_guilds(guild_id) ON DELETE CASCADE;


--
-- Name: x_guilds x_guilds_owner_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.x_guilds
    ADD CONSTRAINT x_guilds_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.x_characters(character_id) ON DELETE CASCADE;


--
-- Name: y_character_items y_character_items_character_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_character_items
    ADD CONSTRAINT y_character_items_character_id_fkey FOREIGN KEY (character_id) REFERENCES public.y_characters(character_id) ON DELETE CASCADE;


--
-- Name: y_character_items y_character_items_item_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_character_items
    ADD CONSTRAINT y_character_items_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.y_items(item_id);


--
-- Name: y_characters y_characters_job_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: student
--

ALTER TABLE ONLY public.y_characters
    ADD CONSTRAINT y_characters_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.y_jobs(job_id);


--
-- PostgreSQL database dump complete
--

\unrestrict 34XxVdFXqv9OqToBbahybrKJJNcPayARtPIZFouOgWEOdkCCTzKLM85KJY1WrSR

